open:
  api:
#    end-point: http://openapi.molit.go.kr/OpenAPI_ToolInstallPackage/service/rest/RTMSOBJSvc/getRTMSDataSvcAptTradeDev?_wadl&type=xml
    end-point: http://openapi.molit.go.kr:8081/OpenAPI_ToolInstallPackage/service/rest/RTMSOBJSvc/getRTMSDataSvcAptTrade
#    service-key: ruGWumGhfqpbu0QB9wx61m7UE9x1%2FbWN9V%2Btk%2BCeiAyIibISDjsloov6ICHpZFtz5KcEn8nsZtJIEee1BIZanw%3D%3D
    service-key: ruGWumGhfqpbu0QB9wx61m7UE9x1/bWN9V+tk+CeiAyIibISDjsloov6ICHpZFtz5KcEn8nsZtJIEee1BIZanw==




#comprehensive-degisn
spring:
  application:
    name: comprehensive-design
  datasource:
    url: jdbc:mysql://localhost:3306/comprehensive-degisn
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: @YOUR_PASSWORD@
  jpa:
    show_sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    open-in-view: false
